#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseHuntingApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HouseHuntingDB")]
	public partial class HouseClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHouse(House instance);
    partial void UpdateHouse(House instance);
    partial void DeleteHouse(House instance);
    #endregion
		
		public HouseClassDataContext() : 
				base(global::HouseHuntingApp.Properties.Settings.Default.HouseHuntingDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HouseClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HouseClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HouseClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HouseClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<House> Houses
		{
			get
			{
				return this.GetTable<House>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Houses")]
	public partial class House : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HouseID;
		
		private string _Type;
		
		private System.Nullable<double> _Price;
		
		private string _Location;
		
		private int _Postcode;
		
		private int _Bedrooms;
		
		private int _Bathrooms;
		
		private int _Carspaces;
		
		private double _Latitude;
		
		private double _Longitude;
		
		private int _priceRating;
		
		private int _houseRating;
		
		private int _safetyRating;
		
		private int _transportRating;
		
		private int _locationRating;
		
		private int _potentialRating;
		
		private double _totalRating;
		
		private double _distanceFromTeganWork;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHouseIDChanging(int value);
    partial void OnHouseIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnPriceChanging(System.Nullable<double> value);
    partial void OnPriceChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnPostcodeChanging(int value);
    partial void OnPostcodeChanged();
    partial void OnBedroomsChanging(int value);
    partial void OnBedroomsChanged();
    partial void OnBathroomsChanging(int value);
    partial void OnBathroomsChanged();
    partial void OnCarspacesChanging(int value);
    partial void OnCarspacesChanged();
    partial void OnLatitudeChanging(double value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(double value);
    partial void OnLongitudeChanged();
    partial void OnpriceRatingChanging(int value);
    partial void OnpriceRatingChanged();
    partial void OnhouseRatingChanging(int value);
    partial void OnhouseRatingChanged();
    partial void OnsafetyRatingChanging(int value);
    partial void OnsafetyRatingChanged();
    partial void OntransportRatingChanging(int value);
    partial void OntransportRatingChanged();
    partial void OnlocationRatingChanging(int value);
    partial void OnlocationRatingChanged();
    partial void OnpotentialRatingChanging(int value);
    partial void OnpotentialRatingChanged();
    partial void OntotalRatingChanging(double value);
    partial void OntotalRatingChanged();
    partial void OndistanceFromTeganWorkChanging(double value);
    partial void OndistanceFromTeganWorkChanged();
    #endregion
		
		public House()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HouseID
		{
			get
			{
				return this._HouseID;
			}
			set
			{
				if ((this._HouseID != value))
				{
					this.OnHouseIDChanging(value);
					this.SendPropertyChanging();
					this._HouseID = value;
					this.SendPropertyChanged("HouseID");
					this.OnHouseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="Int NOT NULL")]
		public int Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bedrooms", DbType="Int NOT NULL")]
		public int Bedrooms
		{
			get
			{
				return this._Bedrooms;
			}
			set
			{
				if ((this._Bedrooms != value))
				{
					this.OnBedroomsChanging(value);
					this.SendPropertyChanging();
					this._Bedrooms = value;
					this.SendPropertyChanged("Bedrooms");
					this.OnBedroomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bathrooms", DbType="Int NOT NULL")]
		public int Bathrooms
		{
			get
			{
				return this._Bathrooms;
			}
			set
			{
				if ((this._Bathrooms != value))
				{
					this.OnBathroomsChanging(value);
					this.SendPropertyChanging();
					this._Bathrooms = value;
					this.SendPropertyChanged("Bathrooms");
					this.OnBathroomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carspaces", DbType="Int NOT NULL")]
		public int Carspaces
		{
			get
			{
				return this._Carspaces;
			}
			set
			{
				if ((this._Carspaces != value))
				{
					this.OnCarspacesChanging(value);
					this.SendPropertyChanging();
					this._Carspaces = value;
					this.SendPropertyChanged("Carspaces");
					this.OnCarspacesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float NOT NULL")]
		public double Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float NOT NULL")]
		public double Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceRating", DbType="Int NOT NULL")]
		public int priceRating
		{
			get
			{
				return this._priceRating;
			}
			set
			{
				if ((this._priceRating != value))
				{
					this.OnpriceRatingChanging(value);
					this.SendPropertyChanging();
					this._priceRating = value;
					this.SendPropertyChanged("priceRating");
					this.OnpriceRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_houseRating", DbType="Int NOT NULL")]
		public int houseRating
		{
			get
			{
				return this._houseRating;
			}
			set
			{
				if ((this._houseRating != value))
				{
					this.OnhouseRatingChanging(value);
					this.SendPropertyChanging();
					this._houseRating = value;
					this.SendPropertyChanged("houseRating");
					this.OnhouseRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_safetyRating", DbType="Int NOT NULL")]
		public int safetyRating
		{
			get
			{
				return this._safetyRating;
			}
			set
			{
				if ((this._safetyRating != value))
				{
					this.OnsafetyRatingChanging(value);
					this.SendPropertyChanging();
					this._safetyRating = value;
					this.SendPropertyChanged("safetyRating");
					this.OnsafetyRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transportRating", DbType="Int NOT NULL")]
		public int transportRating
		{
			get
			{
				return this._transportRating;
			}
			set
			{
				if ((this._transportRating != value))
				{
					this.OntransportRatingChanging(value);
					this.SendPropertyChanging();
					this._transportRating = value;
					this.SendPropertyChanged("transportRating");
					this.OntransportRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locationRating", DbType="Int NOT NULL")]
		public int locationRating
		{
			get
			{
				return this._locationRating;
			}
			set
			{
				if ((this._locationRating != value))
				{
					this.OnlocationRatingChanging(value);
					this.SendPropertyChanging();
					this._locationRating = value;
					this.SendPropertyChanged("locationRating");
					this.OnlocationRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_potentialRating", DbType="Int NOT NULL")]
		public int potentialRating
		{
			get
			{
				return this._potentialRating;
			}
			set
			{
				if ((this._potentialRating != value))
				{
					this.OnpotentialRatingChanging(value);
					this.SendPropertyChanging();
					this._potentialRating = value;
					this.SendPropertyChanged("potentialRating");
					this.OnpotentialRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalRating", DbType="Float NOT NULL")]
		public double totalRating
		{
			get
			{
				return this._totalRating;
			}
			set
			{
				if ((this._totalRating != value))
				{
					this.OntotalRatingChanging(value);
					this.SendPropertyChanging();
					this._totalRating = value;
					this.SendPropertyChanged("totalRating");
					this.OntotalRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distanceFromTeganWork", DbType="Float NOT NULL")]
		public double distanceFromTeganWork
		{
			get
			{
				return this._distanceFromTeganWork;
			}
			set
			{
				if ((this._distanceFromTeganWork != value))
				{
					this.OndistanceFromTeganWorkChanging(value);
					this.SendPropertyChanging();
					this._distanceFromTeganWork = value;
					this.SendPropertyChanged("distanceFromTeganWork");
					this.OndistanceFromTeganWorkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
